[package]
name = "monocaml_playground"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm20-1"] }
lazy_static = "1.5.0"
num-traits = "0.2.19"
rand = "0.9.2"
