[package]
name = "monocaml_playground"
version = "0.1.0"
edition = "2024"

[dependencies]
llvm-sys = "160.0.0"
inkwell = {version = "0.8.0", features = ["llvm16-0"] }
lazy_static = "1.5.0"
num-traits = "0.2.19"
rand = "0.9.2"
tempfile = "3.24.0"
